[project]
name = "pythonmasterlab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.4.0",
    "pandas>=2.3.3",
    "requests>=2.32.3",
    "playwright==1.58.0",
]
